/**
 * Source du logo de chaque service.
 *
 * Trois familles :
 *
 *   { si: 'slug' }        marque officielle issue du paquet `simple-icons`
 *                         (logo réel de la marque, embarqué localement).
 *   { text: 'ARD' }       monogramme / logotype court aux couleurs de la marque,
 *                         pour les diffuseurs et opérateurs absents de
 *                         simple-icons (la plupart ont justement un logo qui est
 *                         un sigle : ARD, TF1, RTBF, SVT…).
 *   { glyph: 'tv' }       pictogramme (voir glyphs.mjs) pour les outils XPENG
 *                         embarqués, qui n'ont pas de marque propre.
 *
 * `hex` est la couleur de la tuile. Pour `si`, elle est reprise du paquet
 * simple-icons si elle n'est pas précisée ici. La couleur du tracé (blanc ou
 * ardoise) est calculée automatiquement à partir du contraste.
 */

const XPENG = '00AEEF';

export const logoMap = {
  // ---------------------------------------------------------------- Vidéo ---
  // Streaming & VOD
  'apple-tv': { si: 'appletv' },
  'disney-plus': { text: 'D+', hex: '113CCF' },
  // simple-icons donne un gris neutre pour « max » : on garde le bleu de la marque.
  'hbo-max': { si: 'max', hex: '002BE7' },
  netflix: { si: 'netflix' },
  'canal-plus': { text: 'CANAL+', hex: '000000' },
  'oqee-tv': { text: 'OQEE', hex: 'E4002B' },
  'xpeng-iptv-player': { glyph: 'tv', hex: XPENG },
  ottplayer: { text: 'OTT', hex: '2563EB' },
  'iptv-org-player': { text: 'IPTV', hex: '18A303' },
  'freestreams-live': { text: 'FS', hex: 'DC2626' },
  'eja-tv': { text: 'eja', hex: '0EA5E9' },
  whostreams: { text: 'WS', hex: '7C3AED' },
  'paramount-plus': { si: 'paramountplus' },
  'prime-video': { text: 'prime', hex: '00A8E1' },
  youtube: { si: 'youtube' },
  peacock: { text: 'peacock', hex: '000000' },
  twitch: { si: 'twitch' },
  vimeo: { si: 'vimeo' },
  crunchyroll: { si: 'crunchyroll' },
  hidive: { text: 'HIDIVE', hex: '00BAFF' },
  dailymotion: { si: 'dailymotion' },
  'pluto-tv': { text: 'pluto', hex: '232D3F' },
  tubi: { si: 'tubi' },
  plex: { si: 'plex' },
  'rakuten-viki': { text: 'viki', hex: '00A0DC' },
  'espn-plus': { text: 'ESPN', hex: 'D40000' },
  dazn: { text: 'DAZN', hex: '000000' },
  'roku-channel': { si: 'roku' },
  xumo: { text: 'xumo', hex: '7B3FE4' },
  stirr: { text: 'stirr', hex: 'E4002B' },
  freevee: { text: 'freevee', hex: '00A8E1' },
  redbox: { text: 'redbox', hex: 'E11B22' },
  vudu: { text: 'vudu', hex: '0072CE' },
  hoopla: { text: 'hoopla', hex: '0DA2A6' },
  kanopy: { text: 'kanopy', hex: 'F4762A' },
  'archive-org': { si: 'internetarchive' },
  hulu: { text: 'hulu', hex: '1CE783' },
  showtime: { si: 'showtime' },
  starz: { si: 'starz' },
  curiositystream: { text: 'CS', hex: '1DBEC5' },
  'xfinity-stream': { text: 'xfinity', hex: '0089CF' },
  'spectrum-tv': { si: 'spectrum' },
  'directv-stream': { text: 'DIRECTV', hex: '00A8E0' },
  'youtube-tv': { si: 'youtubetv' },
  'sling-tv': { text: 'sling', hex: '0075C9' },
  'fubo-tv': { si: 'fubo' },

  // TV gratuite / opérateurs FR
  livestream: { text: 'live', hex: 'CF3A2C' },
  molotov: { text: 'molotov', hex: 'FFCE00' },
  'free-tv-plus': { text: 'Free', hex: 'CD1719' },
  'orange-tv': { si: 'orange' },
  'sfr-tv': { text: 'SFR', hex: 'E2001A' },
  'bouygues-btv': { text: 'B.tv', hex: '009EE0' },
  tvmucho: { text: 'TVM', hex: 'F4511E' },
  arte: { text: 'arte', hex: '000000' },
  francetv: { text: 'ftv', hex: '001E5A' },
  zdf: { si: 'zdf' },

  // Europe
  'francetv-europe': { text: 'ftv', hex: '001E5A' },
  'bbc-iplayer': { text: 'BBC', hex: '000000' },
  'ard-mediathek': { text: 'ARD', hex: '003C78' },
  '6play': { text: 'M6+', hex: 'C0007F' },
  tf1plus: { text: 'TF1+', hex: '002F87' },
  bfmtv: { text: 'BFM', hex: '012D6A' },
  lci: { text: 'LCI', hex: 'E2001A' },
  cnews: { text: 'CNEWS', hex: 'D6001C' },
  rtbf: { text: 'RTBF', hex: 'E30613' },
  rtlplay: { si: 'rtl' },
  pickx: { text: 'pickx', hex: '5C2D91' },
  rtsplay: { text: 'RTS', hex: 'E30613' },
  playsuisse: { si: 'srgssr' },
  'dazn-europe': { text: 'DAZN', hex: '000000' },
  justwatch: { text: 'JW', hex: 'FFB100' },
  'magenta-tv': { si: 'deutschetelekom' },
  'waipu-tv': { text: 'waipu', hex: '00A5E3' },
  'zattoo-eu': { text: 'zattoo', hex: '00A0E9' },
  'joyn-de': { text: 'joyn', hex: 'FF005C' },
  'vodafone-gigatv-de': { si: 'vodafone' },
  'movistar-plus-es': { si: 'movistar' },
  'vodafone-tv-es': { si: 'vodafone' },
  'orange-tv-es': { si: 'orange' },
  atresplayer: { text: 'A3', hex: 'FF5A00' },
  'mitele-es': { text: 'mitele', hex: '0072CE' },
  timvision: { text: 'TIM', hex: '0059FF' },
  raiplay: { text: 'Rai', hex: '003399' },
  'mediaset-infinity-it': { text: 'Infinity', hex: '2E3192' },
  'sky-go-uk': { si: 'sky' },
  'now-tv-uk': { text: 'NOW', hex: '00D6B9' },
  'virgin-tv-go-uk': { si: 'virginmedia' },
  adn: { text: 'ADN', hex: '009FE3' },
  wakanim: { text: 'wakanim', hex: 'EC008C' },
  'npo-start': { text: 'NPO', hex: 'FF6600' },
  nlziet: { text: 'NLZIET', hex: '00A0E0' },
  'svt-play': { text: 'SVT', hex: '00B2A9' },
  'dr-tv': { text: 'DR', hex: '0E4194' },
  'nrk-tv': { text: 'NRK', hex: '00B9F2' },
  'yle-areena': { text: 'Yle', hex: '00B4F0' },
  stan: { text: 'stan', hex: '0072CE' },
  'abc-iview': { text: 'ABC', hex: '1A1A1A' },
  'sbs-on-demand': { text: 'SBS', hex: '009FDF' },
  '7plus': { text: '7plus', hex: 'E4002B' },
  '9now': { text: '9Now', hex: '005EB8' },
  '10play': { text: '10', hex: '003C71' },
  'kayo-sports': { text: 'Kayo', hex: '00D46A' },
  emby: { si: 'emby' },
  jellyfin: { si: 'jellyfin' },

  // Asie
  bilibili: { si: 'bilibili' },
  iqiyi: { text: 'iQ', hex: '00BE06' },
  'tencent-video': { text: 'Tencent', hex: '0052D9' },
  youku: { text: 'YOUKU', hex: '1CC0F3' },
  douyin: { text: 'Douyin', hex: 'FE2C55' },
  'mango-tv': { text: 'Mango', hex: 'FF8200' },

  // Apprentissage
  ted: { si: 'ted' },
  'khan-academy': { si: 'khanacademy' },
  coursera: { si: 'coursera' },
  udemy: { si: 'udemy' },
  skillshare: { si: 'skillshare' },
  masterclass: { text: 'MC', hex: '000000' },
  edx: { si: 'edx' },
  'linkedin-learning': { text: 'in', hex: '0A66C2' },

  // -------------------------------------------------------------- Musique ---
  spotify: { si: 'spotify' },
  'apple-music': { si: 'applemusic' },
  deezer: { si: 'deezer' },
  'youtube-music': { si: 'youtubemusic' },
  tidal: { si: 'tidal' },
  soundcloud: { si: 'soundcloud' },
  'amazon-music': { text: 'music', hex: '25D1DA' },
  pandora: { si: 'pandora' },
  audiomack: { si: 'audiomack' },
  bandcamp: { si: 'bandcamp' },
  mixcloud: { si: 'mixcloud' },
  iheartradio: { si: 'iheartradio' },
  lastfm: { si: 'lastdotfm' },
  tunein: { text: 'tunein', hex: '14D8CC' },
  'bbc-sounds': { text: 'Sounds', hex: 'FF4C98' },
  'radio-france': { si: 'radiofrance' },
  'radioplayer-eu': { text: 'RP', hex: 'E4003B' },
  anghami: { text: 'Anghami', hex: 'A238FF' },
  'qq-music': { text: 'QQ', hex: '31C27C' },
  netease: { text: 'NetEase', hex: 'C20C0C' },

  // ----------------------------------------------------------------- Jeux ---
  'geforce-now': { si: 'nvidia' },
  boosteroid: { text: 'Boost', hex: '6C2BD9' },
  'xbox-cloud': { text: 'Xbox', hex: '107C10' },
  parsec: { text: 'Parsec', hex: '0E1F33' },
  afterplay: { text: 'AP', hex: 'FF3D71' },
  'crazy-games': { text: 'CG', hex: '7B3FE4' },
  poki: { text: 'poki', hex: '0080FF' },
  miniclip: { text: 'mini', hex: '0072CE' },
  'armor-games': { text: 'Armor', hex: 'B21F24' },
  kongregate: { si: 'kongregate' },
  y8: { text: 'Y8', hex: 'FF6600' },
  newgrounds: { si: 'newgrounds' },
  'addicting-games': { text: 'AG', hex: 'F7941E' },
  kizi: { text: 'Kizi', hex: 'FF4E50' },
  friv: { text: 'Friv', hex: '7CB342' },
  agame: { text: 'agame', hex: 'E91E63' },
  retrogames: { text: 'Retro', hex: '7C3AED' },
  gamesnacks: { text: 'GS', hex: 'FBBC04' },
  webrcade: { text: 'wrc', hex: '00C2FF' },
  lego: { text: 'LEGO', hex: 'E3000B' },
  'pbs-kids': { text: 'PBS', hex: '2638C4' },

  // -------------------------------------------------------------- Recharge ---
  'xpeng-map': { glyph: 'pin', hex: XPENG },
  'charger-share': { glyph: 'share', hex: XPENG },
  plugshare: { text: 'PS', hex: '2E7D32' },
  chargepoint: { text: 'CP', hex: '00A9E0' },
  'tesla-supercharger': { si: 'tesla' },
  chargemap: { text: 'CM', hex: '009B4D' },
  waze: { si: 'waze' },
  chargeprice: { text: 'Price', hex: '0AB1B1' },
  abrp: { text: 'ABRP', hex: '2A9FD6' },
  'total-ev-charge': { text: 'Total', hex: 'ED0000' },
  'google-maps': { si: 'googlemaps' },
  windy: { text: 'Windy', hex: '1E88E5' },
  infotrafic: { glyph: 'traffic', hex: 'F59E0B' },

  // ------------------------------------------------- Outils XPENG embarqués ---
  'xpeng-iptv-internal': { glyph: 'tv', hex: XPENG },
  'xpeng-web-calculator': { glyph: 'calculator', hex: XPENG },
  'xpeng-web-notes': { glyph: 'note', hex: XPENG },
  'xpeng-drm-test': { glyph: 'shield', hex: XPENG },
  'xpeng-timer': { glyph: 'clock', hex: XPENG },
  'xpeng-pdf-viewer': { glyph: 'document', hex: XPENG },
  'xpeng-media-guide': { glyph: 'book', hex: XPENG },
  'xpeng-dashcam-viewer': { glyph: 'camera', hex: XPENG },
  'xpeng-trip-planner': { glyph: 'map', hex: XPENG },

  // --------------------------------------------------- Documentation XPENG ---
  'xpeng-g3i-manual': { text: 'G3i', hex: XPENG },
  'xpeng-p5-manual': { text: 'P5', hex: XPENG },
  'xpeng-g6-manual': { text: 'G6', hex: XPENG },
  'xpeng-p7-manual': { text: 'P7', hex: XPENG },
  'xpeng-g9-manual': { text: 'G9', hex: XPENG },
  'xpeng-xmart-os': { text: 'Xmart', hex: XPENG },
  'xpeng-charging-guide': { glyph: 'bolt', hex: XPENG },
  'xpeng-xpilot-guide': { glyph: 'steering', hex: XPENG },
  'xpeng-faq': { glyph: 'question', hex: XPENG },
  'xpeng-service-centers': { glyph: 'wrench', hex: XPENG },
  'google-search': { si: 'google' },

  // ------------------------------------------------------ Communauté XPENG ---
  'xpeng-official': { si: 'youtube' },
  'xpeng-europe': { text: 'EU', hex: XPENG },
  'xpeng-france': { text: 'FR', hex: XPENG },
  'xpeng-tech-reviews': { glyph: 'play', hex: 'FF0000' },
  'xpeng-owners-club': { glyph: 'users', hex: 'FF0000' },
  'ev-reviewers-xpeng': { glyph: 'bolt', hex: 'FF0000' },
  'xpeng-accessories-fr': { text: 'GD', hex: '16A34A' },
  'xpeng-discord': { si: 'discord' },
};
